Feature/classifications front star limit
pedrogab96/portalDisciplinas pull request #36
Opened 2021-04-09 19:56 UTC by kurocaelum

2021-04-11 12:54 UTC, arthurmalakian approved these changes

2021-04-12 14:06 UTC, alvarofpp requested changes

2021-04-12 14:06 UTC, alvarofpp commented on app/Http/Requests/Discipline/StoreRequest.php
>      public function messages()
Remover método `messages()`.

2021-04-12 14:06 UTC, alvarofpp commented on public/js/rating.js
> +    // TODO teste
Isso deveria tá indo nesse PR?

2021-04-12 14:06 UTC, alvarofpp commented on public/js/rating.js
> +// TODO Bugado; Revisar lógica
Isso deveria tá indo nesse PR?

2021-04-12 14:06 UTC, alvarofpp commented on resources/views/disciplines/create.blade.php
> +    <link href="{{asset('css/star-rating.css')}}" media="all" rel="stylesheet" type="text/css" />
CSS deveria estar na section `styles-head`.

2021-04-12 14:06 UTC, alvarofpp commented on resources/views/disciplines/create.blade.php
> +        {{-- mudar para admins --}}
Adiciona um `TODO` no inicio do comentário. Isso facilita encontrar isso pela IDE.

2021-04-12 14:06 UTC, alvarofpp commented on app/Http/Controllers/DisciplineController.php
> +                'classification_id' => 1,
Evitar números aleatórios. Esse 1 pode ser referente a uma classificação X no seu ambiente e no meu ser a classificação Y. Para corrigir isso:
1. Crie um enum que tenha o ID de cada uma das classificações mapeadas nele;
2. Crie um seeder que povoe no banco todas as classificações usando o enum anteriormente criado;
3. Use o enum para referenciar corretamente o ID nesse controller.

2021-04-12 14:06 UTC, alvarofpp commented on app/Http/Requests/Discipline/CreateRequest.php
> +        return !is_null(Auth::user()->professor || Auth::user()->role == RoleName::ADMIN);
Como você usa em vários lugares esse trecho de código (`Auth::user()->role == RoleName::ADMIN`), o ideal seria transformar isso em um método (`isAdmin`).

Espere o PR das faqs ser aceito para usar o accessor is_admin (https://github.com/pedrogab96/portalDisciplinas/blob/47cf92a20475d846d62e565e938a19b74a31e253/app/Models/User.php#L70)

2021-04-12 14:06 UTC, alvarofpp commented on app/Http/Requests/Discipline/StoreRequest.php
> +            // 'classificacao' => ['nullable', 'max:5000',],
Essa validação de `classificacao` nunca será usada (principalmente porque no formulário não tem nenhum input com esse name). Ao invés de comentar, você pode remover essa linha.

Seria interessante colocar uma validação para as classificações.

2021-04-12 14:06 UTC, alvarofpp commented on resources/views/disciplines/create.blade.php
> +                                <input id="apresentacao-trabalhos" name="apresentacao-trabalhos" class="rating rating-loading" data-min="0" data-max="5" data-step="1" value="1" data-size="md" data-sh
Seria interessante padronizar todos os inputs de classificação, exemplo: `classificacao-apresentacao-trabalhos`. Isso irá facilitar na criação das regras de validação no FormRequest.

2021-04-13 12:27 UTC, arthurmalakian commented on app/Http/Requests/Discipline/StoreRequest.php
>      public function messages()
Removido.

2021-04-13 12:29 UTC, arthurmalakian commented on public/js/rating.js
> +    // TODO teste
Isso é um protótipo do sistema  de avaliação de disciplina feito por Victor, não sei a relevância do arquivo no projeto atual

2021-04-13 12:35 UTC, arthurmalakian commented on resources/views/disciplines/create.blade.php
> +    <link href="{{asset('css/star-rating.css')}}" media="all" rel="stylesheet" type="text/css" />
Modificado.

2021-04-13 12:36 UTC, arthurmalakian commented on resources/views/disciplines/create.blade.php
> +        {{-- mudar para admins --}}
Modificado

2021-04-13 13:49 UTC, alvarofpp commented on public/js/rating.js
> +    // TODO teste
Verifique isso, por favor. Caso não tenha relevância, apague o arquivo.

2021-04-14 08:10 UTC, kurocaelum commented on public/js/rating.js
> +    // TODO teste
Deletei aqui, realmente não estava fazendo nada.

2021-04-14 09:08 UTC, kurocaelum commented on app/Http/Requests/Discipline/CreateRequest.php
> +        return !is_null(Auth::user()->professor || Auth::user()->role == RoleName::ADMIN);
Apesar da branch que você refere ter sido aceita, ela não foi integrada a essa branch aqui. 

Não seria melhor aceitar esse PR e depois fazer essa correção direto na development?

2021-04-14 14:46 UTC, alvarofpp commented on app/Http/Requests/Discipline/CreateRequest.php
> +        return !is_null(Auth::user()->professor || Auth::user()->role == RoleName::ADMIN);
Perceba que esse pull request possui conflitos com a branch `development`. Portanto você terá, de um jeito ou de outro, ter que realizar merge com a branch `development`, sendo assim você terá o código necessário para fazer esse ajuste.

2021-04-14 15:10 UTC, alvarofpp requested changes

2021-04-14 15:10 UTC, alvarofpp commented on app/Http/Controllers/DisciplineController.php
> +            return dd($exception);
Remover esse `dd()`.

2021-04-14 15:10 UTC, alvarofpp commented on app/Http/Requests/Discipline/CreateRequest.php
> +        return Auth::user()->getIsAdminAttibute || Auth::user()->getIsProfessorAttibute;
Não sei se você chegou a testar, creio que isso daqui irá dar errado. A forma correta de usar um accessor você poderá ver na documentação [clicando aqui](https://laravel.com/docs/8.x/eloquent-mutators#defining-an-accessor).

2021-04-14 15:10 UTC, alvarofpp commented on app/Http/Requests/Discipline/StoreRequest.php
> +        return Auth::user()->getIsAdminAttribute || Auth::user()->getIsProfessorAttribute;
[Defining An Accessor](https://laravel.com/docs/8.x/eloquent-mutators#defining-an-accessor)

2021-04-14 15:10 UTC, alvarofpp commented on app/Http/Requests/Discipline/StoreRequest.php
>          return [
Remover método `messages()`.

2021-04-14 15:10 UTC, alvarofpp commented on app/Models/User.php
> +        return $this->role() == RoleName::STUDENT;
Isso daqui realmente funciona?

2021-04-14 15:10 UTC, alvarofpp commented on app/Models/User.php
> +        return $this->role() == RoleName::PROFESSOR;
Isso daqui realmente funciona?

2021-04-14 15:10 UTC, alvarofpp commented on app/Models/User.php
> +        return $this->role() == RoleName::ADMIN;
Isso daqui realmente funciona?

2021-04-14 15:10 UTC, alvarofpp commented on composer.json
> +        "willvincent/laravel-rateable": "^2.3"
Até onde consegui ver, esse pacote não está sendo usado. Portanto é mais interessante remover ele.

2021-04-14 15:10 UTC, alvarofpp commented on resources/views/disciplines/create.blade.php
> +    <link href="{{asset('css/star-rating.css')}}" media="all" rel="stylesheet" type="text/css" />
Pelo que eu olhei no código, esse style continua na section errada.

2021-04-14 15:10 UTC, alvarofpp commented on resources/views/disciplines/show.blade.php
> +    <link href="{{asset('css/star-rating.css')}}" media="all" rel="stylesheet" type="text/css" />
CSS na seção errada.

2021-04-15 09:30 UTC, arthurmalakian commented on composer.json
> +        "willvincent/laravel-rateable": "^2.3"
Qual dos?

2021-04-16 18:41 UTC, kurocaelum commented on resources/views/disciplines/create.blade.php
> +    <link href="{{asset('css/star-rating.css')}}" media="all" rel="stylesheet" type="text/css" />
No código que está na minha máquina, está na section certa agora.

2021-04-16 18:44 UTC, alvarofpp approved these changes

2021-04-16 18:44 UTC, merged