Editar disciplina
pedrogab96/portalDisciplinas pull request #53
Opened 2021-04-27 19:09 UTC by arthurmalakian

2021-04-27 21:13 UTC, alvarofpp requested changes

2021-04-27 21:13 UTC, alvarofpp commented on app/Http/Controllers/DisciplineController.php
> +            ClassificationDiscipline::query()->where('discipline_id',$discipline->id)
Você poderia fazer um array mapeando os IDs e os inputs.

```
$classificacoesMap = [
    ClassificationID::AVALIACAO_PROVAS => $request->input('classificacao-av-provas'),
    ClassificationID::AVALIACAO_ATIVIDADES => $request->input('classificacao-av-atividades'),
    // ...
];
```

Aó você só iria precisar percorrer esse array associativo para fazer o update:

```
foreach ($classificacoesMap as $id => $inputValue) {
    ClassificationDiscipline::query()
        ->where('discipline_id', $discipline->id)
        ->where('classification_id', $id)->update([
            'value' => $request->input($inputValue)
        ]);
}
```

2021-04-27 21:13 UTC, alvarofpp commented on app/Http/Requests/Discipline/EditRequest.php
> +        return Auth::user()->is_admin || Auth::user()->is_professor;
Qualquer professor pode editar qualquer disciplina? Se bem me lembro, os professores podem editar apenas disciplinas que correspondem a eles (`professor_id`). Sendo assim, creio que o melhor seria usar o método `canDiscipline()`.

2021-04-27 21:13 UTC, alvarofpp commented on app/Http/Requests/Discipline/UpdateRequest.php
> +        return Auth::user()->is_admin || Auth::user()->is_professor;
Mesma coisa que comentei no EditRequest.

2021-04-27 21:13 UTC, alvarofpp commented on app/Models/Discipline.php
> +    public function getAllClassificationsValues(): ? int
Esse método todinho poderia ser resumido em:
```
$points = $discipline->classificationsDisciplines->sum('value');
```

2021-04-27 21:13 UTC, alvarofpp commented on app/Models/Discipline.php
> +    public function hasTrailerMedia(): bool
Creio que ficaria melhor como Accessor.

```
public function GetHasTrailerMediaAttribute(): bool
```

2021-04-27 21:13 UTC, alvarofpp commented on app/Models/Discipline.php
> +        return $this->medias
```
return $this->medias()->where('is_trailer', true)->exists();
```

2021-04-27 21:13 UTC, alvarofpp commented on resources/views/disciplines/index.blade.php
> +                                      @method('UPDATE')
Para rotas `edit`, o certo é `GET`. Ver a documentação [clicando aqui](https://laravel.com/docs/8.x/controllers#actions-handled-by-resource-controller).

2021-04-27 22:28 UTC, arthurmalakian commented on app/Http/Requests/Discipline/EditRequest.php
> +        return Auth::user()->is_admin || Auth::user()->is_professor;
Para chamar esse método eu precisaria do objeto da disciplina, como eu passo isso pelo edit/update request?

2021-04-29 17:12 UTC, alvarofpp commented on app/Http/Requests/Discipline/EditRequest.php
> +        return Auth::user()->is_admin || Auth::user()->is_professor;
Você pega pelo request. Um exemplo é a classe [`app/Http/Requests/Faq/StoreRequest`](https://github.com/pedrogab96/portalDisciplinas/blob/master/app/Http/Requests/Faq/StoreRequest.php).

2021-05-09 18:54 UTC, alvarofpp approved these changes

2021-05-14 18:46 UTC, pedrogab96 approved these changes

2021-05-17 19:40 UTC, merged